server:
  port: 8002

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/banco
    username: root
    password: 12345
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: transaccion