server:
  port: ${SERVER_PORT:8002}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  
  datasource:
    platform: mysql
    url: ${DB_URI:jdbc:mysql://localhost:3306/banco}
    #url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DATABASE:banco}
    username: root
    password: 12345
    driverClassName: com.mysql.jdbc.Driver

  #datasource:
    #platform: mysql
    #url: jdbc:mysql://localhost:3306/banco
    #username: root
    #password: 12345
    #driverClassName: com.mysql.jdbc.Driver
  
  application:
    name: transaccion

