server:
  port: ${SERVER_PORT:9000}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:

  application:
    name: gateway

  cloud:
    gateway:
      routes:

        - id: empleado
          uri: lb://EMPLEADO
          predicates:
            - Path=/empleado/**
          filters:
            - RewritePath=/empleado/(?<remaining>.*), /$\{remaining}

        - id: transaccion
          uri: lb://TRANSACCION
          predicates:
            - Path=/transaccion/**
          filters:
            - RewritePath=/transaccion/(?<remaining>.*), /$\{remaining}
            
        - id: cuenta
          uri: lb://CUENTA
          predicates:
            - Path=/cuenta/**
          filters:
            - RewritePath=/cuenta/(?<remaining>.*), /$\{remaining}