spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: empleado
          uri: lb://EMPLEADO
          predicates:
            - Path=/empleado/**
          filters:
            - RewritePath=/empleado/(?<remaining>.*), /$\{remaining}
        - id: transaccion
          uri: lb://TRANSACCION
          predicates:
            - Path=/transaccion/**
          filters:
            - RewritePath=/transaccion/(?<remaining>.*), /$\{remaining}
        - id: cuenta
          uri: lb://CUENTA
          predicates:
            - Path=/cuenta/**
          filters:
            - RewritePath=/cuenta/(?<remaining>.*), /$\{remaining}

server:
  port: 9000