server:
  port: ${SERVER_PORT:8888}

 eureka:
   client:
     fetch-registry: true
     register-with-eureka: true
     serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:

  application:
    name: configuracion

  cloud:
    config:
      server:
        git:
          uri: https://github.com/pharaoh583/config_arqui.git
          # ignore-local-ssh-settings: true
          # host-key:
          # host-key-algorithm: ecdsa-sha2-nistp256
          # private-key: