spring:
  application:
    name: configuracion
  cloud:
    config:
      server:
        git:
          uri: 
          ignore-local-ssh-settings: true
          host-key:
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key:

server:
  port: 8888