###Listar cuentas (sin gateway)
GET http://localhost:8002/api/transaccion

###Crear transaccion (sin gateway)
POST http://localhost:8002/api/transaccion
Content-Type: application/json

{
    "eid": 1,
    "coid" : 2,
    "cdid" : 1,
    "amount" : 10.0
}




###Listar cuentas (con gateway)
GET http://localhost:9000/transaccion/api/transaccion

###Crear transaccion (con gateway)
POST http://localhost:9000/transaccion/api/transaccion
Content-Type: application/json

{
    "eid": 1,
    "coid" : 2,
    "cdid" : 1,
    "amount" : 10.0
}