CREATE DATABASE banco;
USE banco;

CREATE TABLE cuenta (
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
amount DECIMAL(12, 2),
status BOOLEAN DEFAULT TRUE,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE empleado (
id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
amount DECIMAL(12, 2),
status BOOLEAN DEFAULT TRUE,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaccion (
id SERIAL NOT NULL PRIMARY KEY,
coid INTEGER REFERENCES cuenta (id),
cdid INTEGER REFERENCES cuenta (id),
eid INTEGER REFERENCES empleado (id),
amount DECIMAL(7, 2),
status BOOLEAN DEFAULT TRUE,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
